import { defaultRules } from './reconciliationEngine.js'
import type { InvoiceCandidate, ReceiptCandidate } from './types.js'

export const receipts: ReceiptCandidate[] = [
  {
    id: 'JE-1001',
    customerId: 'CUST-001',
    subsidiaryId: 'MX-01',
    arAccountId: '1105',
    currency: 'USD',
    amount: 100,
    transactionDate: '2026-04-15',
    postingPeriod: 'Apr 2026',
    reference: 'FAC-9001',
    memo: 'Pago cliente FAC-9001',
  },
  {
    id: 'JE-1002',
    customerId: 'CUST-002',
    subsidiaryId: 'MX-01',
    arAccountId: '1105',
    currency: 'USD',
    amount: 99.2,
    transactionDate: '2026-04-16',
    postingPeriod: 'Apr 2026',
    memo: 'Pago parcial abril',
  },
  {
    id: 'JE-1003',
    customerId: 'CUST-003',
    subsidiaryId: 'MX-01',
    arAccountId: '1105',
    currency: 'USD',
    amount: 100,
    transactionDate: '2026-04-02',
    postingPeriod: 'Apr 2026',
    memo: 'Cobro recibido cierre',
  },
  {
    id: 'JE-1004',
    customerId: 'CUST-004',
    subsidiaryId: 'MX-01',
    arAccountId: '1105',
    currency: 'USD',
    amount: 100,
    transactionDate: '2026-04-12',
    postingPeriod: 'Apr 2026',
    memo: 'Pago cliente sin referencia directa',
  },
]

export const invoices: InvoiceCandidate[] = [
  {
    id: 'INV-9001',
    documentNumber: 'FAC-9001',
    customerId: 'CUST-001',
    subsidiaryId: 'MX-01',
    arAccountId: '1105',
    currency: 'USD',
    openAmount: 100,
    transactionDate: '2026-04-01',
    postingPeriod: 'Apr 2026',
  },
  {
    id: 'INV-9002',
    documentNumber: 'FAC-9002',
    customerId: 'CUST-002',
    subsidiaryId: 'MX-01',
    arAccountId: '1105',
    currency: 'USD',
    openAmount: 100,
    transactionDate: '2026-04-05',
    postingPeriod: 'Apr 2026',
  },
  {
    id: 'INV-9003',
    documentNumber: 'FAC-9003',
    customerId: 'CUST-003',
    subsidiaryId: 'MX-01',
    arAccountId: '1105',
    currency: 'USD',
    openAmount: 100,
    transactionDate: '2026-03-28',
    postingPeriod: 'Mar 2026',
  },
  {
    id: 'INV-9004',
    documentNumber: 'FAC-9004',
    customerId: 'CUST-004',
    subsidiaryId: 'MX-01',
    arAccountId: '1105',
    currency: 'USD',
    openAmount: 100,
    transactionDate: '2026-04-01',
    postingPeriod: 'Apr 2026',
  },
  {
    id: 'INV-9005',
    documentNumber: 'FAC-9005',
    customerId: 'CUST-004',
    subsidiaryId: 'MX-01',
    arAccountId: '1105',
    currency: 'USD',
    openAmount: 100,
    transactionDate: '2026-04-02',
    postingPeriod: 'Apr 2026',
  },
]

export const queueItems = [
  {
    id: 'case-001',
    receiptId: 'JE-1001',
    suggestedAction: 'AUTO_APPLY',
    confidence: 129,
    status: 'ready',
  },
  {
    id: 'case-002',
    receiptId: 'JE-1002',
    suggestedAction: 'REVIEW_TOLERANCE',
    confidence: 92,
    status: 'review',
  },
  {
    id: 'case-003',
    receiptId: 'JE-1003',
    suggestedAction: 'REVIEW_CROSS_PERIOD',
    confidence: 78,
    status: 'period-review',
  },
  {
    id: 'case-004',
    receiptId: 'JE-1004',
    suggestedAction: 'EXCEPTION_CASE',
    confidence: 84,
    status: 'exception',
  },
]

export const auditItems = [
  {
    id: 'audit-1001',
    timestampUtc: '2026-04-16T18:45:00Z',
    actor: 'system.preview',
    message: 'Preview run completed for 4 receipts.',
  },
  {
    id: 'audit-1002',
    timestampUtc: '2026-04-16T18:47:30Z',
    actor: 'finance.supervisor',
    message: 'Adjustment threshold updated to 5.00 USD for MX-01.',
  },
]

export const overview = {
  health: 'healthy',
  pendingReceipts: queueItems.length,
  readyToApply: 1,
  needsReview: 3,
  totalRules: Object.keys(defaultRules).length,
  lastSyncUtc: '2026-04-16T19:00:00Z',
  inventory: {
    inboundLoads: 8,
    activePickWaves: 3,
    cycleCountTasks: 12,
    criticalAlerts: 4,
    occupancyRate: 82,
    stagingUtilizationRate: 64,
    reserveUtilizationRate: 47,
    pickAccuracyRate: 98,
    dispatchReadinessRate: 91,
    recommendedLens: 'recepcion',
  },
}
